import Head from 'next/head'
import Image from 'next/image'
import Login from '../components/Login'
import UserDashboard from '../components/UserDashboard'
import { useAuth } from '../context/AuthContext'

export default function Home() {
  const {currentUser} = useAuth() // useAuth is essentially the useContext hook which allows us to access any of the states we inputted into the contextprovider wrapper in return from AuthContext 
  console.log(currentUser)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      {!currentUser && <Login/>} {/* if current user is null then display login */}
      {currentUser && <UserDashboard/>} {/* if current user is logged in, or not null, display userDashboard  */}
    </>
  )
}
